---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# efiplusr

<!-- badges: start -->
<!-- badges: end -->

The goal of efiplusr is to ...

## Installation

You can install the development version of efiplusr from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("AnthonyBasooma/efiplusr")
```

## Example

The example code is used to run test the European Fish Index.

```{r example}
library(efiplusr)
#The fish data required 

data("inputdata")

# row code preparation
inputdata$code <- paste(inputdata$Site.code,inputdata$Day,inputdata$Month,inputdata$Year,sep="_")

labs <- c("WQO2.O2INTOL", "HTOL.HINTOL",  "HabSp.RHPAR",  "Repro.LITH")
type1 <- c("dens","dens","ric","dens")

labels2 <- c("WQO2.O2INTOL","HTOL.HINTOL")
type2 <- rep("dens",2)

output <- fi_index(x=inputdata, 
                     species = "Species", 
                     code = "code", 
                     runs = "Total.number.run1",
                     region = "Ecoreg",
                     medtype = "Medit",
                     lat = "Latitude",
                     slope = "Actual.river.slope",
                     tempjan = "Temp.jan",
                     tempjul = "Temp.jul",
                     water = "Water.source.type",
                     sediment = "Natural.sediment",
                     geomorph = "Geomorph.river.type",
                     method = "Method",
                     area = "Area.ctch",
                     floodpsite = "Floodplain.site",
                     distsource = "Distance.from.source",
                     len_up = "Number.length.over.150",
                     len_down = "Number.length.below.150", 
                     efitype = "Eft.type",
                     labels = labs,
                     type = type1,
                     type2 = type2,
                     labels2 = labels2,
                     salmonidindex = c("dens.WQO2.O2INTOL","dens.HTOL.HINTOL"),
                     cyprinidindex = c("ric.HabSp.RHPAR","dens.Repro.LITH"))
```


